language: node_js
node_js: 10.14.1

services: docker

before_install:
  - sudo apt-get update
  - sudo apt-get install rpl
  - npm install -g codecov

before_script:
  - cd backend
  - cp .env.example .env.testing
  - rpl dev test .env.testing

env:
  - CODECOV_TOKEN="a72c65b4-7ce0-472c-b960-c822fa15960f"  

script: npm run testing

branches:
  only:
    - "master"

after_success:
  - docker cp covid-19-test:/usr/local/coverage/lcov.info ./
  - codecov --file ./lcov.info --disable search