version: "3"
services:
  covid-19-app:
    build: .
    depends_on:
      - covid-19-db
    environment:
      PORT: 8080
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: covid19
    ports:
      - "8080:8080"
    links:
      - covid-19-db
  covid-19-db:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: covid19