version: '3.4'

networks:
  covid-19:

services:

  covid-19-app:
    build: .
    depends_on:
      - covid-19-db
    environment:
      PORT: 8080
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: covid19
    ports:
      - "8080:8080"
    networks:
      - covid-19

  covid-19-db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: covid19
    ports:
      - "35432:5432"
    networks:
      - covid-19