FROM node:10.14.1-alpine

WORKDIR /usr/src/

COPY package*.json /usr/src/

RUN npm install
RUN npm install -g nodemon

COPY src /usr/src/src

EXPOSE 8080
EXPOSE 9229
ENV NODE_ENV development

CMD ["npm", "run", "start:dev"]