version: '3.4'

services:
  covid-19-dev:
    build: .
    env_file:
      - .env.example
    depends_on:
      - covid-19-db
    ports:
      - "8080:8080"
    networks:
      - covid-19
    volumes:
      - .:/home/node/app

    # Example for production environment
    # covid-19-app:
    #   build: .
    #   depends_on:
    #     - covid-19-db
    #   ports:
    #     - "80:8080"
    #   networks:
    #     - covid-19

  covid-19-db:
    image: postgres:12
    env_file:
      - .env.example
    ports:
      - "35432:5432"
    networks:
      - covid-19

networks:
  covid-19:
