version: "3.4"

services:
  covid-19-dev:
    container_name: covid-19-test
    env_file:
      - .env.testing
    command: ["npm", "run", "start:test"]
    environment:
      - NODE_ENV="testing"
  
  covid-19-db-dev:
    env_file:
      - .env.testing
