version: "3.4"

services:
  covid-19:
    build: .
    container_name: covid-19
    env_file:
      - .env
    depends_on:
      - covid-19-db
    ports:
      - "443:443"
    networks:
      - covid-19

  covid-19-db:
    image: postgres:12-alpine
    container_name: covid-19-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - covid-19

networks:
  covid-19: