version: "3.4"

services:
  covid-19-test:
    build:
      context: ./
      dockerfile: Dockerfile.testing
    container_name: covid-19-test
    env_file:
      - .env.testing
    environment:
      - WAIT_HOSTS=covid-19-db-test:5432
    depends_on:
      - covid-19-db-test
    networks:
      - covid-19

  covid-19-db-test:
    image: postgres:12-alpine
    container_name: covid-19-db-test
    env_file:
      - .env.testing
    networks:
      - covid-19

networks:
  covid-19: