FROM node:10.14.1-alpine

WORKDIR /usr/local/
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.2/wait /wait

COPY package*.json /usr/local/

RUN npm install

COPY src /usr/local/src

RUN chmod +x /wait

ENV NODE_ENV testing

CMD /wait && npm run start:test