version: "3.4"

services:
  covid-19-dev:
    build:
      context: .
      args:
        - NODE_ENV="development"
    container_name: covid-19-dev
    ports:
      - "9229:9229"
      - "8080:8080"
    volumes:
      - ./src:/usr/local/src
    env_file:
      - .env
    command: ["npm", "run", "start:dev"]
    networks:
      - covid-19
  
  covid-19-db:
    image: postgres:12-alpine
    container_name: covid-19-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - covid-19

networks:
  covid-19:
