version: "3.4"

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3030:3030"
    stdin_open: true
    volumes:
      - ./src:/usr/local/src
      - ./public:/usr/local/public